services:
  # === Client ===
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - "8000:80"
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  # === Server ===
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "7000:7000"
    volumes:
      - ./server:/server
    depends_on:
      - database
    command: >
      sh -c "
      python server/wait_for_db.py &&
      python manage.py runserver 0.0.0.0:7000"
    env_file:
      - ./.env
  
  # === Database ===
  database:
    image: postgres:17.1-alpine3.20
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - ./.env

volumes:
  database: